name: Deploy

on:
  push:
    branches: [main]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: ./dist

  frontend-deploy:
    needs: frontend-build
    runs-on: ubuntu-latest
    environment:
      name: cf-pages
    steps:
      - uses: actions/setup-node@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ./dist

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ secrets.CF_PAGES_PROJECT }}
